pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                // Tus comandos de construcción
            }
        }
        stage('Test') {
            steps {
                // Tus comandos de prueba
            }
        }
        // ... otros stages
    }
    
    // AQUÍ ES DONDE DEBE IR EL POST GLOBAL
    post {
        always {
            echo 'Pipeline terminado.'
        }
        success {
            echo '¡El Pipeline fue exitoso!'
        }
        failure {
            echo '¡El Pipeline falló!'
        }
    }
}