pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                // Tus comandos de construcción
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                // Tus comandos de prueba
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                // Tus comandos de despliegue
                echo "Simulando un despliegue en un servidor de aplicaciones"
            }
        }
    }
    
    // AQUÍ ES DONDE DEBE IR EL POST GLOBAL
    post {
        always {
            echo 'Pipeline terminado.'
        }
        success {
            echo '¡El Pipeline fue exitoso!'
        }
        failure {
            echo '¡El Pipeline falló!'
        }
    }
}